# (PART\*) INTRODUCTION {-}

# C-MOOR Overview

### An Introduction to Data Science

Data Science is an evolving career path for individuals (data scientists) in fields that need to manipulate large amounts of data. The job of a Data Scientist was called by the Harvard Business Review "[the sexiest job of the 21st century](https://hbr.org/2012/10/data-scientist-the-sexiest-job-of-the-21st-century)" Data Scientists are individuals with a curiosity to look through data, identify patterns and develop testable hypotheses.  In Biological Sciences, data scientists dig through data to answer questions about health, disease, evolution, ecology, drug development, and much more. A currently relevant example is compiling and looking at the similarities and differences between the different SARS-CoV-2 strains and identify differences between strains that may lead to differences in rates of infection.

### What is C-MOOR?

C-MOOR is a project to invite students to join the data science revolution and be part of the next generation of data scientists.  This project provides online materials to help students and instructors incorporate authentic research experiences in lower division courses.  To learn more about its presence at Clovis Community College, visit https://www.cloviscollege.edu/alumni-and-community/c-moor/c-moor.html

### Learning Goals

1. Engage with real and current scientific data
1. Explore available research resources online
1. Recognize the interdisciplinary nature of biological sciences
1. Synthesize findings from scientific literature
1. Summarize findings and discuss results with your peers
1. Collaborate with peers on a data exploration activity
